version: "3.9"

services:

  python:
    build:
      context: ./backend
      args:
        PYTHON_TAG: ${PYTHON_TAG}
        BACKEND_PORT: $BACKEND_PORT
        APP_PACKAGE_NAME: "socimg:application"
        WSGI_APP: $WSGI_APP
    container_name: "${PROJECT_NAME}_python"
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      FLASK_ENV: $PYTHON_FLASK_ENV
      FLASK_APP: $PYTHON_FLASK_APP
      FLASK_RUN_HOST: $PYTHON_FLASK_HOST
      APP_CONFIG_FILE: $APP_CONFIG_FILE
    volumes:
    - ./backend:/code
    labels:
     - "traefik.http.routers.${PROJECT_NAME}_backend.rule=Host(`backend.${PROJECT_BASE_URL}`)"

  mysql:
    image: mysql:$MYSQL_TAG
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: "${PROJECT_NAME}_mysql"
    stop_grace_period: 30s
    ports:
      - 8083:3306
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_DATABASE: $MYSQL_DATABASE
    volumes:
      - ./data/db:/var/lib/mysql
    
  redis:
    container_name: "${PROJECT_NAME}_redis"
    image: redis:$REDIS_TAG

  phpmyadmin:
    container_name: "${PROJECT_NAME}_phpmyadmin"
    image: phpmyadmin
    restart: always
    # ports:
    #   - $PHPMYADMIN_PORT:80
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: $MYSQL_ROOT_PASSWORD
    labels:
     - "traefik.http.routers.${PROJECT_NAME}_phpmyadmin.rule=Host(`phpmyadmin.${PROJECT_BASE_URL}`)"

  traefik:
    image: traefik:v2.4
    container_name: "${PROJECT_NAME}_traefik"
    command: --api.insecure=true --providers.docker
    ports:
      - '8081:80'
      - '8001:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
     - "traefik.http.routers.${PROJECT_NAME}_portrainer.rule=Host(`portrainer.${PROJECT_BASE_URL}`)"
